version: '3.9'

services:
  moneymonkey:
    image: moneymonkey
    container_name: python_moneymonkey
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - USER_NAME=${USER_NAME:-appuser}
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
      RUNNING_IN_DOCKER: "true"
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - .:/app:cached
    depends_on:
      - mysql
    networks:
      - moneymonkey_network

  mysql:
    image: mysql:8.4
    container_name: mysql_moneymonkey
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./data/db/mysql:/var/lib/mysql
      - ./data/mysql_run:/var/run/mysqld
    networks:
      - moneymonkey_network
    command: mysqld --pid-file=/var/run/mysqld/mysqld.pid

networks:
  moneymonkey_network:
    name: moneymonkey_network
